// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mihntsnilfkxeriyqbar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1paG50c25pbGZreGVyaXlxYmFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MTY5MDYsImV4cCI6MjA3MTk5MjkwNn0.km4CA6wMEI6u_83pTARowkfOSpqZj9oA4_WE_-ZXEsY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});